name: me
description: Ravi's Portfolio.

publish_to: "none"

version: 1.0.0+2

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_web_plugins:
    sdk: flutter

  cupertino_icons: ^1.0.5
  lottie: ^3.0.0
  font_awesome_flutter: ^10.6.0
  url_launcher: ^6.2.4
  http: ^1.2.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  string_contains: ^2.3.0
  webview_flutter: ^4.4.4
  webview_flutter_web: ^0.2.2+4
  hydrated_bloc: ^9.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  icons_launcher: ^2.1.7

flutter:
  uses-material-design: true

  assets:
    - assets/animations/
    - fonts/

  fonts:
    - family: Urbanist
      fonts:
        - asset: fonts/Urbanist-Regular.ttf
