name: me
description: Ravi's Portfolio.
publish_to: "none"
version: 1.0.0+2

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_web_plugins:
    sdk: flutter

  # ui & animation dependencies
  cupertino_icons: ^1.0.8
  lottie: ^3.3.1
  google_fonts: ^6.2.1
  flutter_lucide: ^1.6.2

  # utility dependencies
  url_launcher: ^6.3.1
  http: ^1.3.0
  string_contains: ^2.4.0

  # state management dependencies
  flutter_bloc: ^9.1.0
  hydrated_bloc: ^10.0.0
  equatable: ^2.0.7

  # webview dependencies
  webview_flutter: ^4.10.0
  webview_flutter_web: ^0.2.3+4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  icons_launcher: ^3.0.1
  flutter_native_splash: ^2.4.5

flutter:
  uses-material-design: true

  assets:
    - assets/animations/
    
